#spring.application.name=palomalumi
#spring.datasource.url=psql 'postgresql://neondb_owner:npg_EX8PvbKNpMc6@ep-summer-bar-acgeeljx-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
#spring.datasource.username=neondb
#spring.datasource.password=npg_EX8PvbKNpMc6
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update




# Nome da aplicação
spring.application.name=Palomalumi

# Configurações do Neon (PostgreSQL)
###spring.datasource.url=jdbc:postgresql://ep-summer-bar-acgeeljx-pooler.sa-east-1.aws.neon.tech/neondb
spring.datasource.url=jdbc:postgresql://localhost/aves?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=postgre
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_EX8PvbKNpMc6
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA/Hibernate para PostgreSQL
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Configurações do Pool de Conexão (HikariCP)
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.port=8083
spring.jpa.open-in-view=false